site_name: Mailbatch
repo_url: https://github.com/systopia/de.systopia.mailbatch
edit_uri: https://github.com/systopia/de.systopia.mailbatch
site_description: 'Documentation for the Mailbatch Extension (de.systopia.mailbatch)'
site_author: 'SYSTOPIA'
theme:
  name:
    material

nav:
  - Start: index.md
  - Introduction: basics.md
  - Installation: installation.md
  - Usage: usage.md
  
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
